[package]
name = "tmi-network-bridge"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
async-trait = "0.1.42"
futures = "0.3.12"
tracing = "0.1.22"
tracing-futures = "0.2.4"
tmi-primitives = { path = "../../../primitives" }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
sc-authority-discovery = { git = "https://github.com/tmi/substrate", branch = "master" }
sc-network = { git = "https://github.com/tmi/substrate", branch = "master" }
tmi-subsystem = { package = "tmi-node-subsystem", path = "../../subsystem" }
tmi-node-network-protocol = { path = "../protocol" }
strum = "0.20.0"

[dev-dependencies]
assert_matches = "1.4.0"
parking_lot = "0.11.1"
tmi-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
tmi-node-subsystem-util = { path = "../../subsystem-util"}
sp-core = { git = "https://github.com/tmi/substrate", branch = "master" }
sp-keyring = { git = "https://github.com/tmi/substrate", branch = "master" }
