[package]
name = "tmi-node-jaeger"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "tmi Jaeger primitives"

[dependencies]
async-std = "1.8.0"
mick-jaeger = "0.1.4"
lazy_static = "1.4"
parking_lot = "0.11.1"
tmi-primitives = { path = "../../primitives" }
sc-network = { git = "https://github.com/tmi/substrate", branch = "master" }
sp-core = { git = "https://github.com/tmi/substrate", branch = "master" }
thiserror = "1.0.23"
log = "0.4.13"
