[package]
name = "tmi-cli"
version = "0.8.28"
authors = ["Parity Technologies <admin@parity.io>"]
description = "tmi Relay-chain Client Node"
edition = "2018"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.13"
thiserror = "1.0.23"
structopt = { version = "0.3.21", optional = true }
wasm-bindgen = { version = "0.2.69", optional = true }
wasm-bindgen-futures = { version = "0.4.19", optional = true }
futures = "0.3.12"

service = { package = "tmi-service", path = "../node/service", default-features = false, optional = true }
tmi-parachain = { path = "../parachain", optional = true }

sp-core = { git = "https://github.com/tmi/substrate", branch = "master" }
tracing-futures = "0.2.4"
frame-benchmarking-cli = { git = "https://github.com/tmi/substrate", branch = "master", optional = true }
sc-cli = { git = "https://github.com/tmi/substrate", branch = "master", optional = true }
sc-service = { git = "https://github.com/tmi/substrate", branch = "master", optional = true }
browser-utils = { package = "substrate-browser-utils", git = "https://github.com/tmi/substrate", branch = "master", optional = true }

# this crate is used only to enable `trie-memory-tracker` feature
# see https://github.com/tmi/substrate/pull/6745
sp-trie = { git = "https://github.com/tmi/substrate", branch = "master", default-features = false }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/tmi/substrate", branch = "master" }

[features]
default = [ "wasmtime", "db", "cli", "full-node", "trie-memory-tracker", "tmi-parachain" ]
wasmtime = [ "sc-cli/wasmtime", "tmi-parachain/wasmtime" ]
db = [ "service/db" ]
cli = [
	"structopt",
	"sc-cli",
	"sc-service",
	"frame-benchmarking-cli",
]
browser = [
	"wasm-bindgen",
	"wasm-bindgen-futures",
	"browser-utils",
	"service",
]
runtime-benchmarks = [ "service/runtime-benchmarks" ]
trie-memory-tracker = [ "sp-trie/memory-tracker" ]
full-node = [ "service/full-node" ]
real-overseer = [ "service/real-overseer" ]
